# Generated by Django 3.2 on 2022-11-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, verbose_name='Razon Social o \n nombre de empresa')),
                ('representante', models.CharField(max_length=50, verbose_name='Nombre completo del representante')),
                ('cuit', models.CharField(max_length=50, verbose_name='CUIT de la empresa')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion de la empresa')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono de la empresa')),
                ('email', models.CharField(max_length=50, verbose_name='Email de la empresa')),
                ('fecha', models.DateField(verbose_name='Fecha de alta')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
