# Generated by Django 3.2 on 2022-11-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres del Cliente')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos del Cliente')),
                ('dni', models.CharField(max_length=50, verbose_name='DNI')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('fecha', models.DateField(verbose_name='Fecha de alta')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
